DROP TABLE IF EXISTS pulse_weekly;
DROP TABLE IF EXISTS meeting_attendees;
DROP TABLE IF EXISTS meetings;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE employees (
    employee_id INTEGER PRIMARY KEY,
    department_id INTEGER NOT NULL REFERENCES departments(department_id),
    seniority VARCHAR(20) NOT NULL CHECK (seniority IN ('junior', 'mid', 'senior', 'manager')),
    hourly_rate NUMERIC(12, 2) NOT NULL CHECK (hourly_rate > 0),
    annual_salary NUMERIC(14, 2) NOT NULL CHECK (annual_salary > 0)
);

CREATE TABLE meetings (
    meeting_id INTEGER PRIMARY KEY,
    meeting_date DATE NOT NULL,
    department_id INTEGER NOT NULL REFERENCES departments(department_id),
    meeting_type VARCHAR(30) NOT NULL CHECK (meeting_type IN ('status_update', 'brainstorm', 'decision_making', 'one_on_one', 'all_hands')),
    duration_mins INTEGER NOT NULL CHECK (duration_mins > 0),
    attendee_count INTEGER NOT NULL CHECK (attendee_count > 0),
    organizer_seniority VARCHAR(20) NOT NULL CHECK (organizer_seniority IN ('junior', 'mid', 'senior', 'manager')),
    is_recurring BOOLEAN NOT NULL,
    recurring_series_id VARCHAR(64),
    is_disproportionately_expensive BOOLEAN NOT NULL,
    duration_was_imputed BOOLEAN NOT NULL,
    duration_outlier_flag BOOLEAN NOT NULL
);

CREATE TABLE meeting_attendees (
    meeting_id INTEGER NOT NULL REFERENCES meetings(meeting_id),
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id),
    attendee_seniority VARCHAR(20) NOT NULL CHECK (attendee_seniority IN ('junior', 'mid', 'senior', 'manager')),
    attendee_department_id INTEGER NOT NULL REFERENCES departments(department_id),
    hourly_rate NUMERIC(12, 2) NOT NULL CHECK (hourly_rate > 0),
    row_cost NUMERIC(14, 2) NOT NULL CHECK (row_cost >= 0),
    PRIMARY KEY (meeting_id, employee_id)
);

CREATE TABLE pulse_weekly (
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id),
    week_start DATE NOT NULL,
    department_id INTEGER NOT NULL REFERENCES departments(department_id),
    seniority VARCHAR(20) NOT NULL CHECK (seniority IN ('junior', 'mid', 'senior', 'manager')),
    hours_in_meetings NUMERIC(6, 2) NOT NULL CHECK (hours_in_meetings >= 0),
    self_reported_productivity SMALLINT NOT NULL CHECK (self_reported_productivity BETWEEN 1 AND 10),
    self_reported_burnout SMALLINT NOT NULL CHECK (self_reported_burnout BETWEEN 1 AND 10),
    productivity_was_imputed BOOLEAN NOT NULL,
    burnout_was_imputed BOOLEAN NOT NULL,
    PRIMARY KEY (employee_id, week_start)
);

CREATE INDEX idx_employees_department_id ON employees(department_id);
CREATE INDEX idx_meetings_department_id ON meetings(department_id);
CREATE INDEX idx_meeting_attendees_employee_id ON meeting_attendees(employee_id);
CREATE INDEX idx_meeting_attendees_attendee_department_id ON meeting_attendees(attendee_department_id);
CREATE INDEX idx_pulse_weekly_department_id ON pulse_weekly(department_id);
